In [2]:
from sklearn.decomposition import PCA
import numpy as np

X = np.array([
    [170, 65, 25],
    [160, 60, 24],
    [180, 75, 28],
    [175, 70, 26]
])

print("Original Data:")
print(X)

# PCA to reduce dimensions
pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X)

print("Reduced Data (3D → 2D):")
print(X_reduced)


Original Data:
[[170  65  25]
 [160  60  24]
 [180  75  28]
 [175  70  26]]
Reduced Data (3D → 2D):
[[ -2.58758424  -1.28392269]
 [-13.60747678   0.84341928]
 [ 11.71005439   0.85520394]
 [  4.48500663  -0.41470053]]
